resources:
  - name: gitcheck
    type: GitRepo
    configuration:
      gitProvider: test
      path: seekhJaunga/xyz
pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          env1: 
            default: "singletest"
            values: ["singletest", "testing"]
            allowCustom: false
          env2: "test_p2"
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          inputResources:
            - name: gitcheck
        execution:
          onExecute:
            - printenv
            - echo $env1
            - echo res_test_path
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          chronological: true
          affinityGroup: trigger
          inputSteps: 
            - name: trigger_1
        execution:
          onExecute:
            - printenv
            - echo $env3
            - echo ${#env3[@]}
            - echo ${env3[2]}
            - echo "Running second trigger done"
