resources:
  - name: gitcheck
    type: GitRepo
    configuration:
      gitProvider: test
      path: seekhJaunga/Ekart
  - name: gitcheck1
    type: GitRepo
    configuration:
      gitProvider: test
      path: seekhJaunga/AntiTheft
pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          env: 
            default: "singletest"
            values: ["singletest", "testing"]
            allowCustom: false
          env2: "test_p2"
          # env3:
          #   defaultMultipleValues: ["r,andom_1", "r,andom_4"]
          #   description: "testing"
          #   values: ["r,andom_1", "r,andom_2", "r,andom_3", "r,andom_4"]
          #   allowCustom: false
          #   allowMultipleValues: true
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          inputResources:
            - name: gitcheck
        execution:
          onExecute:
            - printenv
            - echo $env1
            - echo res_test_path
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          chronological: true
          affinityGroup: trigger
          inputSteps: 
            - name: trigger_1
        execution:
          onExecute:
            - printenv
            - echo ${#env3[@]}
            - echo ${env3[2]}
            - echo "Running second trigger done"
