# resources:
#   - name: resource_1
#     type: GitRepo
#     configuration:
#       gitProvider: test
#       path: seekhJaunga/Ekart
#       buildOn:
#          commit: false
#   - name: resource_4
#     type: GitRepo
#     configuration:
#       gitProvider: test
#       path: seekhJaunga/Ekart

# resources:
#   - name: propertyBag_1
#     type: PropertyBag
#     configuration:
#       property1: "jfrog"
#       property2: "pipelines"
pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          env: 
            default: "singletest"
            values: ["singletest", "testing"]
            allowCustom: false
          env2: "test_p2"
          env3:
            defaultMultipleValues: ["r,andom_1"]
            # default: "r,andom_2"
            description: "testing"
            values: ["r,andom_1", "r,andom_2", "r,andom_3", "r,andom_4"]
            allowCustom: false
            allowMultipleValues: true
    steps:
      # - name: step_1
      #   type: Bash
      #   configuration:
      #     integrations:
      #       - name: testing
      #   execution:
      #     onExecute:
      #       - echo $int_testing_val1
      #       - echo $int_testing_val2
      #       - |
      #         if [ $int_testing_val1 = "password1" ]; then
      #           echo matched
      #         else
      #           echo NotMatched
      #         fi
      #       - |
      #         if [ $int_testing_val2 = "password2" ]; then
      #           echo matched
      #         else
      #           echo NotMatched
      #         fi
      - name: trigger_3
        type: PowerShell
        configuration:
          affinityGroup: trigger
          # inputResources:
          #   # - name: propertyBag_1
          #   - name: resource_4
          #   - name: resource_1
        execution:
          onExecute:
            # - printenv
            - echo $env1
            - echo $res_resource_1_path
            - echo $res_resource_3_path
            - echo "done"
      - name: trigger_4
        type: PowerShell
        configuration:
          # inputResources:
          #   # - name: propertyBag_1
          chronological: true
          affinityGroup: trigger
          inputSteps: 
            - name: trigger_3
            # - name: step_1
        execution:
          onExecute:
            # - printenv
            - echo ${#env3[@]}
            - echo ${env3[2]}
            - echo "Running second trigger done"
            - $env3.Length
            - $env3
            - $env2
            - $env
            - $env2.length
            - $env3[0]
            - $env3[1]
            - $env3[2]
            - $env3[3]
            - $env3[4]
            # - echo $int_testing_
            # - echo $int_testing_
