pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          env1: "test_p1"
          env2: "test_p2"
          env3:
            default: "random_1"
            multiDefault: ["random_1", "random_4"]
            description: "testing"
            values: ["random_1", "random_2", "random_3", "random_4"]
            allowCustom: false
            allowMulti: true
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
        execution:
          onExecute:
            - printenv
            - echo step_configuration_environmentVariables
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          chronological: true
          affinityGroup: trigger
          inputSteps: 
            - name: trigger_1
        execution:
          onExecute:
            - printenv
            - echo "Running second trigger done"
