resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: test
      path: seekhJaunga/Ekart
      cloneProtocol: https
      buildOn:
         commit: true
  - name: resource_3
    type: GitRepo
    configuration:
      gitProvider: test
      path: seekhJaunga/AntiThef
      cloneProtocol: https
pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          env: 
            default: "singletest"
            values: ["singletest", "testing"]
            allowCustom: false
          env2: "test_p2"
          env3:
            defaultMultipleValues: ["r,andom_1"]
            description: "testing"
            values: ["r,andom_1", "r,andom_2", "r,andom_3", "r,andom_4"]
            allowCustom: false
            allowMultipleValues: true
    steps:
      # - name: step_1
      #   type: Bash
      #   configuration:
      #     integrations:
      #       - name: testing
      #   execution:
      #     onExecute:
      #       - echo $int_testing_test1
      #       - echo $int_testing_test2
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          inputResources:
            - name: resource_1 
            - name: resource_2
        execution:
          onExecute:
            - printenv
            - echo $env1
            - echo $res_resource_1_path
            - echo $res_resource_2_path
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          chronological: true
          affinityGroup: trigger
          inputSteps: 
            - name: trigger_1
            # - name: step_1
        execution:
          onExecute:
            - printenv
            - echo ${#env3[@]}
            - echo ${env3[2]}
            - echo "Running second trigger done"
            # - echo $int_testing_
            # - echo $int_testing_
