pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          env1: "test_p1"
          env2: "test_p2"
          env3:
            defaultMultipleValues: ["r,andom_1 f", "f r,andom_4"]
            description: "testing"
            values: ["r,andom_1f", "r,andom_2", "r,andom_3", "fr,andom_4"]
            allowCustom: false
            allowMultipleValues: true
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
        execution:
          onExecute:
            - printenv
            - echo $env3
            - echo ${#env3[@]}
            - echo ${env3[2]}
            - echo "Running second trigger done"
