pipelines:
  - name: single_test
    configuration:
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 5
      environmentVariables:
        readOnly:
          env1: "test_p1"
          env2: "test_p2"
          env3:
            multiDefault: ["r,andom_1", "r,andom_4"]
            description: "testing"
            values: ["r,andom_1", "r,andom_2", "r,andom_3", "r,andom_4"]
            allowCustom: false
            allowMulti: true
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
        execution:
          onExecute:
            - printenv
            - echo $env1
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          chronological: true
          affinityGroup: trigger
          inputSteps: 
            - name: trigger_1
        execution:
          onExecute:
            - printenv
            - echo $env3
            - echo ${#env3[@]}
            - echo ${env3[2]}
            - echo "Running second trigger done"
