resources:
  # - name: prores
  #   type: PropertyBag
  #   configuration:
  #     runNumber: 56
  #     x: 55
  - name: gitRes1
    type: GitRepo
    configuration:
      gitProvider: finalTest
      path: seekhJaunga/pipelineBasic
      buildOn:
         branchCreate: false
         commit: false
  - name: env_params
    type: PropertyBag
    configuration:
      xsc_ci_config_branch_name: ''
      d2c_server_name: ''
      d2c_url: ''
      d2c_job_extra_params: ''
      cell_id: ''
      docker_repo_name: ''
      jf_msi: ''
pipelines:
  - name: newPip1
    configuration:
      environmentVariables:
        readOnly:
          env2: '''test_p2 {BRANCH_NAME_HASH}'''
          env1: pipe_value1.abc
          env5:
            default: pipe_value2
            description: This is env2 description
            secure: true
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          inputResources:
            - name: gitRes1
          outputResources:
            - name: env_params
          # outputResources:
          #   - name: prores
        execution:
          onExecute:
            - printenv
            - echo $env
            - echo $env2
            # - write_output "env_params" ""
            # - write_output myResource runNumber=${run_number}



# resources:
#   - name: gosvc_promoted_build_info1
#     type: BuildInfo
#     configuration:
#       sourceArtifactory: s_artifactory
#       buildName: svc_build
#       buildNumber: 1
  # - name: S_CreateReleaseBundle_0001_output
  #   type: ReleaseBundle
  #   configuration:
  #     sourceDistribution: s_distribution
  #     name: name
  #     version: '1'

# pipelines:
#   - name: demo_release_mgmt5
#     steps:
#       - name: bundle
#         type: CreateReleaseBundle
#         configuration:
#           releaseBundleName: demo_rb
#           releaseBundleVersion: v1.0
#           dryRun: false
#           sign: false
#           description: some random test description
#           inputResources:
#             - name: gosvc_promoted_build_info1
#               trigger: true
#           outputResources:
#             - name: S_CreateReleaseBundle_0001_output
#           releaseNotes:
#             syntax: markdown
#             content: |
#               ## Heading
#                 * Bullet
#                 * Points
