template: true
valuesFilePath: ./values.yml

{{ range $env := .Values.Environments }}
pipelines:
  - name:  {{ .Values.ServiceName }}_Multi_Tenancy
    steps:
      - name: EXT_S_SYC_AU_0007
        type: Bash
        execution:
          onExecute:
            - echo hehe
{{end}}
