resources:
  - name: prores
    type: PropertyBag
    configuration:
      runNumber: 0
      x: 5
  - name: gitRes
    type: GitRepo
    configuration:
      gitProvider: finalTest
      path: seekhJaunga/pipelineBasic
      buildOn:
         branchCreate: false
         commit: false
pipelines:
  - name: newPip
    configuration:
      environmentVariables:
        readOnly:
          env2: "test_p2"
          env1: pipe_value1
          env5:
            default: pipe_value2
            description: This is env2 description
            secure: true
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          inputResources:
            - name: gitRes
          outputResources:
            - name: prores
        execution:
          onExecute:
            - printenv
            - echo $env
            - echo $env2
            - write_output myResource runNumber=${run_number}
